# Generated by Django 2.0.7 on 2018-08-03 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('9aefd196-3624-426e-adc8-2e40f4efecd4'), max_length=64, verbose_name='Identification key'),
        ),
    ]
