# Generated by Django 2.0.7 on 2018-08-05 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0002_auto_20180803_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('06b7829a-9e70-408d-a43d-98a9b5e5c750'), max_length=64, verbose_name='Identification key'),
        ),
    ]
