# Generated by Django 2.0.7 on 2018-08-06 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0002_auto_20180803_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('fc7347b1-8362-49ad-90c9-b6f8f190138f'), max_length=64, verbose_name='Identification key'),
        ),
    ]
