# Generated by Django 2.0.7 on 2018-08-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0003_auto_20180805_0811'),
        ('fil_auth', '0005_auto_20180806_0527'),
    ]

    operations = [
    ]
