# Generated by Django 2.0.7 on 2018-08-06 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0006_merge_20180806_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('3287406d-2ea3-446f-a450-bc6ab5568738'), max_length=64, verbose_name='Identification key'),
        ),
    ]
