# Generated by Django 2.0.7 on 2018-08-06 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0006_merge_20180806_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('62a870cf-dfbd-4778-96bd-9965580d4ffe'), max_length=64, verbose_name='Identification key'),
        ),
    ]
