# Generated by Django 2.0.7 on 2018-08-06 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0008_auto_20180806_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('241354c1-6d89-41e1-be3b-2f44be0de5a6'), max_length=64, verbose_name='Identification key'),
        ),
    ]
