# Generated by Django 2.0.7 on 2018-08-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0007_auto_20180806_0544'),
        ('fil_auth', '0009_auto_20180806_0719'),
    ]

    operations = [
    ]
