# Generated by Django 2.0.7 on 2018-08-06 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0010_merge_20180806_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('b9be607b-7b04-4b53-b8c6-285878b4ebc8'), max_length=64, verbose_name='Identification key'),
        ),
    ]
