# Generated by Django 2.0.7 on 2018-08-06 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0011_auto_20180806_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('65ba8398-01c6-4f79-b610-ee841f55798c'), max_length=64, verbose_name='Identification key'),
        ),
    ]
