# Generated by Django 2.0.7 on 2018-08-07 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0012_auto_20180806_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('b32185b1-eae7-4043-9635-6f5eda3ff300'), max_length=64, verbose_name='Identification key'),
        ),
    ]
