# Generated by Django 2.0.7 on 2018-08-07 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0013_auto_20180807_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('af629ee4-20dd-4a48-a1dd-b84b666b59af'), max_length=64, verbose_name='Identification key'),
        ),
    ]
