# Generated by Django 2.0.7 on 2018-08-07 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0014_auto_20180807_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('edeffbbf-de67-4cb4-ae14-e9a16a7b694e'), max_length=64, verbose_name='Identification key'),
        ),
    ]
