# Generated by Django 2.0.7 on 2018-08-07 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fil_auth', '0015_auto_20180807_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idf',
            field=models.CharField(default=uuid.UUID('2e180685-1f2f-489b-a866-faf4c346ae38'), max_length=64, verbose_name='Identification key'),
        ),
    ]
