# Generated by Django 2.0.7 on 2018-08-07 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180807_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default=uuid.UUID('99bb9b65-d8d8-4ca2-8fe5-660eadeec9d1'), max_length=64, primary_key=True, serialize=False, verbose_name='Event Id'),
        ),
    ]
